name: Local
variables:
    - name: baseUrl
      value: http://localhost:3000
      enabled: true
      secret: false
      type: text
    - name: booking_charge_key
      value: ''
      enabled: true
      secret: true
      type: text
    - name: auth_token
      value: ''
      enabled: true
      secret: true
      type: text
