name: Local
variables:
    - name: baseUrl
      value: https://5txni3482h.execute-api.us-east-2.amazonaws.com
      enabled: true
      secret: false
      type: text
    - name: booking_charge_key
      value: ekwkljfbwerkvb
      enabled: true
      secret: true
      type: text
    - name: auth_token
      value: ''
      enabled: true
      secret: true
      type: text
