name: Production
variables:
    - name: baseUrl
      value: https://your-prod-api-url.execute-api.us-east-1.amazonaws.com
      enabled: true
      secret: false
      type: text
    - name: booking_charge_key
      value: ''
      enabled: true
      secret: true
      type: text
    - name: auth_token
      value: ''
      enabled: true
      secret: true
      type: text
