/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AuthService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "BillingService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "NotificationService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SiteDocuments": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SiteService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TestService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}