/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AdminService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthUserPoolV2": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "BookingChargeKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BookingQueryService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BookingService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DocumentService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "IncidentQueryService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "IncidentService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "NotificationService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PaymentService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SiteDocuments": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SiteService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SiteVerificationService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SubscriptionService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TestService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UserService": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}

import "sst"
export {}