import {
    LayoutDashboard,
    Users,
    Map,
    Plane,
    Settings,
    Bell,
    Search,
    Command,
    LifeBuoy,
    Send,
    Calendar,
    ShieldAlert,
    FileCheck,
    AlertCircle,
    ShieldCheck,
    UserCheck,
    CreditCard,
    AlertTriangle,
    BarChart3,
    MapPin,
    CalendarClock,
    Wallet,
} from 'lucide-react';

export const data = {
    user: {
        name: 'Demo User',
        email: 'demo@example.com',
        avatar: 'https://github.com/shadcn.png',
    },
    teams: [
        {
            name: 'VertiAccess',
            logo: Command,
            plan: 'Enterprise',
        },
    ],
    navSecondary: [
        {
            title: 'Support',
            url: '#',
            icon: LifeBuoy,
        },
        {
            title: 'Feedback',
            url: '#',
            icon: Send,
        },
    ],
    notifications: [
        {
            id: '1',
            title: 'New Site Request',
            description: 'A new site has been submitted for verification.',
            time: '2 minutes ago',
            unread: true,
        },
        {
            id: '2',
            title: 'Booking Confirmed',
            description: 'Your booking for Site A has been confirmed.',
            time: '1 hour ago',
            unread: true,
        },
        {
            id: '3',
            title: 'System Update',
            description: 'Platform maintenance scheduled for tonight.',
            time: 'Yesterday',
            unread: false,
        },
        {
            id: '4',
            title: 'New Message',
            description: 'You have a new message from Support.',
            time: '2 days ago',
            unread: false,
        },
        {
            id: '5',
            title: 'Security Alert',
            description: 'New login detected from a new device.',
            time: '3 days ago',
            unread: true,
        },
        {
            id: '6',
            title: 'Payment Received',
            description: 'Your payment for the Enterprise plan has been received.',
            time: '4 days ago',
            unread: false,
        },
        {
            id: '7',
            title: 'Profile Updated',
            description: 'Your profile information has been successfully updated.',
            time: '5 days ago',
            unread: false,
        },
        {
            id: '8',
            title: 'New Feature',
            description: 'Check out the new analytics dashboard!',
            time: '1 week ago',
            unread: true,
        },
    ],
};

export const roleNavItems = {
    admin: [
        { title: 'Overview', url: '/dashboard/admin', icon: LayoutDashboard },
        { title: 'Landowner Verifications', url: '/dashboard/admin/verifications/landowner', icon: ShieldCheck },
        { title: 'Operator Verifications', url: '/dashboard/admin/verifications/operator', icon: UserCheck },
        { title: 'Site Verifications', url: '/dashboard/admin/verifications/sites', icon: Map },
        { title: 'Subscription Plans', url: '/dashboard/admin/subscriptions', icon: CreditCard },
        { title: 'User Management', url: '/dashboard/admin/users', icon: Users },
        { title: 'Safety & Incidents', url: '/dashboard/admin/incidents', icon: AlertTriangle },
        { title: 'Analytics', url: '/dashboard/admin/analytics', icon: BarChart3 },
    ],
    landowner: [
        { title: 'Overview', url: '/dashboard/landowner', icon: LayoutDashboard },
        { title: 'My Sites', url: '/dashboard/landowner/sites', icon: MapPin },
        { title: 'Booking Requests', url: '/dashboard/landowner/requests', icon: CalendarClock },
        { title: 'Incident Reports', url: '/dashboard/landowner/incidents', icon: AlertCircle },
        { title: 'Balance', url: '/dashboard/landowner/balance', icon: Wallet },
        { title: 'Billing', url: '/dashboard/billing', icon: CreditCard },
        { title: 'Settings', url: '/dashboard/landowner/settings', icon: Settings },
    ],
    operator: [
        { title: 'Dashboard', url: '/dashboard/operator', icon: LayoutDashboard },
        { title: 'Search & Discovery', url: '/dashboard/operator/search', icon: Search },
        { title: 'My Bookings', url: '/dashboard/operator/bookings', icon: Calendar },
        { title: 'Emergency & Recovery', url: '/dashboard/operator/emergency', icon: ShieldAlert },
        { title: 'Consent Certificates', url: '/dashboard/operator/consent', icon: FileCheck },
        { title: 'Incident Reports', url: '/dashboard/operator/incidents', icon: AlertCircle },
        { title: 'Billing', url: '/dashboard/billing', icon: CreditCard },
        { title: 'Settings', url: '/dashboard/operator/settings', icon: Settings },
    ],
};
